django/zzapstargram/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup, name="signup")
	, path('login/', views.login, name="login")
	, path('logout/', views.logout, name="logout")

	, path('<int:user_id>/', views.user_page, name="user_page")
	, path('<int:user_id>/follow/', views.follow, name="follow")
	, path('<int:user_id>/update/', views.update, name="update")
]

django/zzapstargram/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
	path('', views.index, name="index")
	, path('all/', views.all, name="all")
	, path('<int:post_id>/', views.detail, name="detail")
	, path('create/', views.create, name="create")
	, path('<int:post_id>/update/', views.update, name="update")
	, path('<int:post_id>/delete/', views.delete, name="delete")
	# 댓글 작성
	, path('<int:post_id>/comment/create/', views.comment_create, name="comment_create")
	, path('<int:post_id>/comment/update/', views.comment_update, name="comment_update")
	, path('<int:post_id>/comment/delete/', views.comment_delete, name="comment_delete")
	# 좋아요
	, path('<int:post_id>/likes/', views.likes, name="likes")
	# hashtag
	, path('hashtags/<int:hashtag_id>/', views.hashtags, name="hashtags")
]

django/zzapstargram/zzapstargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls)
	# , path('posts/', include('posts.urls'))
	, path('', include('posts.urls'))
	, path('accounts/', include('accounts.urls'))
	, path('accounts/', include('allauth.urls'))
]
# urlpatterns += static('/media/')로 바꿔도 무방함
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/zzapstargram/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.
class User(AbstractUser, models.Model):
	# 클래스가 완성되지 않은 상태에서 User클래스를 만드려면 오류가 뜸
	# 그래서 꼼수로 settings.AUTH_USER_MODEL 쓰면 됨
	follow = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="follower")
	introduce = models.TextField(blank=True)
	image = ProcessedImageField(upload_to='posts/images',
	                            processors=[ResizeToFill(300, 200)],
	                            format='JPEG',
	                            options={'quality': 90},
	                            blank=True)

django/zzapstargram/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


# Create your models here.
class HashTag(models.Model):
	content = models.CharField(max_length=50, unique=True)

	def __str__(self):
		return self.content

class Post(models.Model):
	# related_name
	# 유저모델과 포스트모델을 연결시키려함
	# 근데 아래에 똑같은 settings.AUTH_USER_MODEL 모델을 사용헀음
	# 그래서 다르게 해주기 위해 related_name을 지정해서 충돌 방지
	like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	content = models.TextField()
	# image = models.ImageField(blank=True)
	# Django Imagekit
	image = ProcessedImageField(upload_to='posts/images',
	                            processors=[ResizeToFill(300, 200)],
	                            format='JPEG',
	                            options={'quality': 90})
	hash_tags = models.ManyToManyField(HashTag, blank=True)


class Comment(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

django/zzapstargram/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		# fields = '__all__'
		# 대괄호 소괄호 차이 없는거??
		# fields = ['username', 'email']
		fields = ['username']


class CustomUserChangeForm(UserChangeForm):
	password = None

	class Meta:
		model = User
		# fields = '__all__'
		fields = [
			'email'
			, 'introduce'
			, 'image'
		]

# class Meta 생성 이유
#

django/zzapstargram/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from .forms import *
from .models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
	if request.user.is_authenticated:
		return redirect('posts:index')
	if request.method == "GET":
		form = CustomUserCreationForm()
	else:
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			auth_login(request, user)
			return redirect('posts:index')
	return render(request, 'accounts/signup.html', {
		'form': form
	})


def login(request):
	if request.user.is_authenticated:
		return redirect('posts:index')
	if request.method == "GET":
		form = AuthenticationForm()
	else:
		form = AuthenticationForm(request, request.POST)
		if form.is_valid():
			auth_login(request, form.get_user())
			return redirect('posts:index')
	return render(request, 'accounts/login.html', {
		'form': form
	})


def logout(request):
	auth_logout(request)
	return redirect('posts:index')


def user_page(request, user_id):
	user_info = User.objects.get(id=user_id)
	context = {
		'user_info': user_info
	}
	return render(request, 'accounts/user_page.html', context)


@login_required
def follow(request, user_id):
	user = request.user
	follow_user = User.objects.get(id=user_id)

	if user != follow_user:
		# 너를 팔로우 하는 사람들 목록에 내가 있으면
		if user in follow_user.follower.all():
			follow_user.follower.remove(user)
		else:
			follow_user.follower.add(user)
	# return redirect('accounts:user_page', user_id)
	return redirect('posts:index')


@login_required
def update(request, user_id):
	user = User.objects.get(id=user_id)
	if request.user == user:
		if request.method == 'GET':
			form = CustomUserChangeForm(instance=user)
		else:
			form = CustomUserChangeForm(request.POST, request.FILES, instance=user)
			if form.is_valid():
				form.save()
				return redirect("accounts:user_page", user_id)
		return render(request, 'accounts/form.html', {
			'form': form
			,
		})
	return redirect('accounts:user_page', user_id)

django/zzapstargram/accounts/templates/accounts/form.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block title %}회원수정폼{% endblock %}

{% block body %}
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type="submit" class="btn btn-outline-primary">정보수정</button>
</form>
{% endblock %}

django/zzapstargram/accounts/templates/accounts/login.html
{% extends 'posts/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block title %}회원가입폼{% endblock %}

{% block body %}
<form action="" method="POST">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type="submit" class="btn btn-outline-primary">로그인</button>
</form>
<a href="{% provider_login_url 'kakao' %}"><img src="{% static 'accounts/images/login/kakao_account_login_btn_large_wide.png' %}" alt="kakao-login" width="400" height="70"></a>
<br>
<a href="{% provider_login_url 'naver' %}"><img src="{% static 'accounts/images/login/네이버 아이디로 로그인_완성형_Green.PNG' %}" alt="naver-login" width="400" height="70"></a>


{% endblock %}

django/zzapstargram/accounts/templates/accounts/signup.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block title %}회원가입폼{% endblock %}

{% block body %}
<form action="" method="POST">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type="submit" class="btn btn-outline-primary">등록</button>
</form>
{% endblock %}

django/zzapstargram/accounts/templates/accounts/user_page.html
{% extends 'posts/base.html' %}
{% block title %}{% endblock %}

{% block body %}
<div class="row">
	<div class="col-4 d-flex justify-content-center">
		<!--프로필이미지넣는공간-->
		{% if user_info.image %}
			<img src="{{user_info.image.url}}" class="rounded-pill">
		{% else %}
			<img src="https://picsum.photos/id/{{user_info.id}}/1000/150" class="rounded-pill">
		{% endif %}
	</div>
	<div class="col-8">
		<!--정보가 보여지는공간-->
		<h3>{{ user_info.username}}</h3>
		{% if user != user_info %}
			{% if user in user_info.follower.all %}
				<a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-outline-danger">팔로우 취소</a>
			{% else %}
				<a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-primary">팔로우</a>
			{% endif %}
		{% else %}
		<a href="{% url 'accounts:update' user.id %}" class="btn btn-warning">회원정보 수정</a>
		{% endif %}
		<div class="d-flex justify-content-between">
			<p>게시물 {{ user_info.post_set.count }}</p>
			<p>팔로워 {{ user_info.follower.count }}</p>
			<p>팔로우 {{ user_info.follow.count }}</p>
		</div>
		<div>
			{{ user_info.introduce }}
		</div>
	</div>
</div>
<div class="card-columns">
	{% for post in user_info.post_set.all %}
		{% include 'posts/_post.html' %}
	{% endfor %}
</div>

{% endblock %}