django/zzapstargram/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup, name="signup")
	, path('login/', views.login, name="login")
	, path('logout/', views.logout, name="logout")

	, path('<int:user_id>/', views.user_page, name="user_page")
	, path('<int:user_id>/follow/', views.follow, name="follow")
	, path('<int:user_id>/update/', views.update, name="update")
]

django/zzapstargram/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
	path('', views.index, name="index")
	, path('all/', views.all, name="all")
	, path('<int:post_id>/', views.detail, name="detail")
	, path('create/', views.create, name="create")
	, path('<int:post_id>/update/', views.update, name="update")
	, path('<int:post_id>/delete/', views.delete, name="delete")
	# 댓글 작성
	, path('<int:post_id>/comment/create/', views.comment_create, name="comment_create")
	, path('<int:post_id>/comment/update/', views.comment_update, name="comment_update")
	, path('<int:post_id>/comment/delete/', views.comment_delete, name="comment_delete")
	# 좋아요
	, path('<int:post_id>/likes/', views.likes, name="likes")
	# hashtag
	, path('hashtags/<int:hashtag_id>/', views.hashtags, name="hashtags")
]

django/zzapstargram/zzapstargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls)
	# , path('posts/', include('posts.urls'))
	, path('', include('posts.urls'))
	, path('accounts/', include('accounts.urls'))
	, path('accounts/', include('allauth.urls'))
]
# urlpatterns += static('/media/')로 바꿔도 무방함
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/zzapstargram/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


# Create your models here.
class HashTag(models.Model):
	content = models.CharField(max_length=50, unique=True)

	def __str__(self):
		return self.content

class Post(models.Model):
	# related_name
	# 유저모델과 포스트모델을 연결시키려함
	# 근데 아래에 똑같은 settings.AUTH_USER_MODEL 모델을 사용헀음
	# 그래서 다르게 해주기 위해 related_name을 지정해서 충돌 방지
	like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	content = models.TextField()
	# image = models.ImageField(blank=True)
	# Django Imagekit
	image = ProcessedImageField(upload_to='posts/images',
	                            processors=[ResizeToFill(300, 200)],
	                            format='JPEG',
	                            options={'quality': 90})
	hash_tags = models.ManyToManyField(HashTag, blank=True)


class Comment(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

django/zzapstargram/posts/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		# fields = '__all__'
		fields = ['content', 'image']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		# fields = '__all__'
		fields = ['content']

django/zzapstargram/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import *
from django.contrib.auth.decorators import login_required
from itertools import chain
from django.http import JsonResponse


# Create your views here.
def index(request):
	# posts = Post.objects.all().order_by('-id')
	user = request.user
	if user.is_authenticated:
		user_follow = user.follow.all()
		follow_list = chain(user_follow, [request.user])
		posts = Post.objects.order_by('-id').filter(user__in=follow_list)
	else:
		posts = Post.objects.all().order_by('-id')
	return render(request, 'posts/index.html', {
		'posts': posts
		, 'comment_form': CommentForm()
	})


def all(request):
	posts = Post.objects.all().order_by('-id')

	return render(request, 'posts/index.html', {
		'posts': posts
		, 'comment_form': CommentForm()
	})


def detail(request, post_id):
	return render(request, 'posts/detail.html', {
		'post': Post.objects.get(id=post_id)
	})


@login_required
def create(request):
	# 1. GET 방식으로 데이터를 입력할 수 있는 form 요청
	# 4. 사용자가 데이터를 입력해서 post 요청을 보냄
	# 9. 사용자가 적절한 데이터를 입력해서 post요청을 보낸다.
	if request.method == "GET":
		# 2. PostForm을 인스턴스화 해서 form 변수에 저장
		form = PostForm()
	else:
		# 5. post방식으로 저장요청을 받고, 데이터를 받아서 PostForm을 인스턴스화 함
		# 10. 데이터를 받아서 postform을 인스턴스화 한다.
		form = PostForm(request.POST, request.FILES)
		# 6. 데이터 검증을 함
		# 11. 데이터 검증을 한다
		if form.is_valid():
			# 12. valid 하면 저장
			post = form.save(commit=False)
			post.user = request.user
			post.save()

			# 해시태그 추가
			content = form.cleaned_data.get('content')
			words = content.split()

			for word in words:
				if word[0] == "#":
					# 해시태그 생성
					# 중복 처리, 배열을 뱉음
					# 0번째는 객체, 1번째는 가져와 졌는지 못가져왔는지
					hashTag = HashTag.objects.get_or_create(content=word)
					# 해시태그와 post를 연결
					post.hash_tags.add(hashTag[0])

			return redirect('posts:index')
		else:
			# 7. 적절하지 않은 데이터가 들어옴
			pass
	# 3. 만들어진 form을 create.html에 담아서 전송
	# 8. 사용자가 정확하게 입력한 데이터를 유지한 상태의 form을 전송
	return render(request, 'posts/form.html', {
		'form': form
	})


@login_required
def update(request, post_id):
	post = Post.objects.get(id=post_id)
	if request.user == post.user or request.user.username == 'admin':
		# 내가 작성한 글일 때
		if request.method == "GET":
			form = PostForm(instance=post)
		else:
			form = PostForm(request.POST, request.FILES, instance=post)

			if form.is_valid():
				post = form.save(commit=False)
				post.user = request.user
				post.save()

				post.hash_tags.clear()

				content = form.cleaned_data.get('content')
				words = content.split()

				for word in words:
					if word[0] == "#":
						hashTag = HashTag.objects.get_or_create(content=word)
						post.hash_tags.add(hashTag[0])
				return redirect('posts:index')

		return render(request, 'posts/form.html', {
			'form': form
		})
	else:
		# 내가 작성하지 않은 글일 때
		return redirect('posts:index')


@login_required
def delete(request, post_id):
	post = Post.objects.get(id=post_id)
	post.delete()
	return redirect('posts:index')


# 댓글다는곳
@login_required
def comment_create(request, post_id):
	post = Post.objects.get(id=post_id)
	if request.method == 'POST':
		comment_form = CommentForm(request.POST)
		if comment_form.is_valid():
			comment = comment_form.save(commit=False)
			comment.post = post
			comment.user = request.user
			comment.save()
		return redirect('posts:index')
	return render(request, 'posts/index.html', {
		'comment_form': CommentForm()
	})


def comment_update(request, post_id):
	return


def comment_delete(request, post_id):
	return


@login_required
def likes(request, post_id):
	user = request.user
	post = Post.objects.get(id=post_id)

	# 이미 좋아요가 눌러졌으면
	if user in post.like_users.all():
		# 좋아요 취소
		post.like_users.remove(user)
		is_like = False
	# 좋아요 안했으면
	else:
		# 좋아요
		post.like_users.add(user)
		is_like = True

	# return redirect('posts:index')
	like_count = post.like_users.count()
	return JsonResponse({
		'is_like': is_like,
		'like_count': like_count
	})


def hashtags(request, hashtag_id):
	hashtag = HashTag.objects.get(id=hashtag_id)
	posts = hashtag.post_set.all()

	comment_form = CommentForm()
	return render(request, 'posts/index.html', {
		'posts': posts
		, 'comment_form': comment_form
		, 'hashtag': hashtag
	})


def javascript(request):
	return render(request, 'posts/javascript.html', {

	})

django/zzapstargram/posts/templates/posts/_post.html
{% load bootstrap4 %}
{% load posts_templatetag %}
{% if request.resolver_match.url_name == 'index' or request.resolver_match.url_name == 'all' %}
<div class="card col-3 my-3">
{% else %}
<div class="card">
{% endif %}
    {% if post.image %}
    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
    {% else %}
    <img src="https://picsum.photos/id/{{ post.id }}/280/200" class="card-img-top" alt="...">
    {% endif%}
    <div class="card-body">
        <h5 class="card-title">{{ post.id }}</h5>
        <p class="card-text"><a href="{% url 'accounts:user_page' post.user.id %}"><strong>{{ post.user.username }}</strong></a> {{ post|hashtag_link|safe }}</p>
        <span id="like-count-{{post.id}}">{{post.like_users.count}} 명이 좋아합니다</span>
        <p class="text-right">
            {% if post.user == user or user.id == 1 %}
            <a class="btn btn-primary" href="{% url 'posts:update' post.id %}" role="button">수정</a>
            <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}" role="button">삭제</a> {% endif %}
        </p>
        {% if user in post.like_users.all %}
        <i class="fas fa-heart-broken like-heart" data-id="{{post.id}}"></i>
        {% else %}
        <i class="fas fa-heart like-heart" style="color:red" data-id="{{post.id}}"></i>
        {% endif %}
        <form action="{% url 'accounts:follow' post.user.id %}">
            {% if user in post.user.follower.all %}
            <button type="submit" class="btn btn-outline-danger">팔로우 취소 <i class="fas fa-heart-broken"></i>{{ post.user.follower.count }}</button>
            {% else %}
            <button type="submit" class="btn btn-outline-primary">팔로우 <i class="fas fa-heart"></i>{{ post.user.follower.count }}</button>
            {% endif %}
        </form>
    </div>

	{% if request.resolver_match.url_name == 'index' or request.resolver_match.url_name == 'all' %}
    <!--댓글 출력-->
    <div class="card-body">
        {% for comment in post.comment_set.all %}
        <strong>{{ comment.user }}</strong>
        <p>{{ comment.content }}</p>
        {% empty %}
        <p>댓글이 없습니다</p>
        {% endfor %}
    </div>
    <!--댓글 폼 시작-->
    <div class="card-body">
        <form action="{% url 'posts:comment_create' post.id%}" method="post">
            {% csrf_token %} {% bootstrap_form comment_form %}
            <button type="submit" class="btn btn-outline-primary">댓글등록</button>
        </form>
    </div>
    <!--댓글 폼 끝-->
	{% endif %}
</div>

django/zzapstargram/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'posts:index' %}"><i class="fab fa-instagram"></i> 짭스타그램</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:all' %}">전체보기</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">새글작성</a>
                </li>

            </ul>
        </div>

        <div class="navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated == False %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:update' user.id %}">회원정보수정</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_page' user.id %}">{{ user }}님 반갑습니다</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
	<div class="container">
    {% block body %} {% endblock %}
	</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<!--font awesome-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
    const likeButtons = document.querySelectorAll('.like-heart')
    likeButtons.forEach(function(button){
        button.addEventListener('click', (e)=>{
            const postId = e.target.dataset.id
            axios.get(`/${postId}/likes/`).then(function(res){
                const likeCount = document.querySelector(`#like-count-${postId}`)
                likeCount.innerText = res.data.like_count + "명이 좋아합니다"
                if(res.data.is_like){
                    e.target.classList.remove('fa-heart')
                    e.target.classList.add('fa-heart-broken')
                    e.target.style.color = 'black'
                }
                else {
                    e.target.classList.remove('fa-heart-broken')
                    e.target.classList.add('fa-heart')
                    e.target.style.color = 'red'
                }
            })
        })
    })
    </script>
</body>

</html>

django/zzapstargram/posts/templates/posts/form.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block title %}{% endblock %}

{% block body %}
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type="submit" class="btn btn-outline-primary">등록</button>
</form>
{% endblock %}

django/zzapstargram/posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block title %}짭스타그램{% endblock %}

{% block body %}
{% if request.resolver_match.url_name == 'index' %}
	<h1>index</h1>
{% elif request.resolver_match.url_name == 'all' %}
	<h1>전체목록</h1>
{% else %}
	<h1>{{ hashtag }}</h1>
{% endif %}
<div class="row">
	{% for post in posts %}
		{% include 'posts/_post.html' %}
	{% endfor %}
</div>
{% endblock %}

django/zzapstargram/posts/templates/posts/javascript.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>

</head>
<body>
	<div id="me">

	</div>
	<button id="my-button">test</button>
</body>
</html>