django/board_sample/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
	path('', views.index, name="index"),

	# article
	path('<int:article_id>/', views.detail, name="detail"),
	# path('create_form/', views.create_form, name="create_form"),
	path('create/', views.create, name="create"),
	# path('<int:article_id>/update_form/', views.update_form, name="update_form"),
	path('<int:article_id>/update/', views.update, name="update"),
	path('<int:article_id>/delete/', views.delete, name="delete"),

	# comment
	path('<int:article_id>/comments/create/', views.create_comment, name='create_comment'),
	path('<int:article_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),

	path('get_comments/', views.get_comments, name="get_comments")
]

django/board_sample/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
	path('', views.index, name="index"),
	path('<int:board_id>/detail/', views.detail, name="detail"),

	path('create/', views.create, name="create"),

	path('<int:board_id>/update/', views.update, name="update"),

	path('<int:board_id>/delete/', views.delete, name="delete"),
]

django/board_sample/board_sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('board/', include('board.urls')),
]

django/board_sample/articles/models.py
from django.db import models
from django.conf import settings
# setting.AUTH_USER.Model


# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# CASCADE : 폭포
# on_delete : CASCADE 게시물이 삭제되면 폭포처럼 댓글도 다 지워버린다.
class Comment(models.Model):
	content = models.TextField()  # 댓글
	article = models.ForeignKey(Article, on_delete=models.CASCADE)  # Article Class Foreign Key
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

django/board_sample/board/models.py
from django.db import models


# Create your models here.
class Board(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()

django/board_sample/articles/views.py
from django.shortcuts import render, redirect
from .models import *


# Create your views here.
def index(request):
	return render(request, 'articles/index.html', {
		'title': '인덱스입니다',
		'articles': Article.objects.all(),
	})


def detail(request, article_id):
	article = Article.objects.get(id=article_id)
	return render(request, 'articles/detail.html', {
		'title': '디테일 페이지 입니다',
		'article': article,
	})


def create_form(request):
	return render(request, 'articles/create_form.html')


def create(request):
	if request.method == "GET":
		return render(request, 'articles/form.html')
	else:
		title = request.POST.get('title')
		content = request.POST.get('content')

		article = Article()
		article.title = title
		article.content = content
		article.user = request.user
		article.save()

		return redirect('articles:index')


def update_form(request, article_id):
	article = Article.objects.get(id=article_id)
	return render(request, 'articles/update_form.html', {
		'title': '업데이트폼',
		'article': article,
	})


def update(request, article_id):
	if request.method == "GET":
		article = Article.objects.get(id=article_id)
		return render(request, 'articles/form.html', {
			'title': '업데이트폼',
			'article': article,
		})
	else:
		article = Article.objects.get(id=request.POST.get('id'))
		article.title = request.POST.get('title')
		article.content = request.POST.get('content')
		article.save()
		return redirect('/articles/')


def delete(request, article_id):
	Article.objects.get(id=article_id).delete()
	return redirect('articles:index')


# Comment
def create_comment(request, article_id):
	comment_new = Comment()
	comment_new.content = request.POST.get('content')
	comment_new.article = Article.objects.get(id=article_id)
	comment_new.user = request.user
	comment_new.save()
	return redirect('articles:detail', article_id)


def delete_comment(request, article_id, comment_id):
	article_selected = Article.objects.get(id=article_id)
	comment_selected = article_selected.comment_set.get(id=comment_id)
	comment_selected.delete()
	return redirect('articles:detail', article_id)


def get_comments(request):
	return render(request, 'articles/get_comments.html', {
		'user': request.user,
	})

django/board_sample/board/views.py
from django.shortcuts import render, redirect
from .models import Board


# Create your views here.
def index(request):
	boards = Board.objects.all()
	return render(request, 'board/index.html', {
		'title': '인덱스 페이지',
		'boards': boards,
	})


def detail(request, board_id):
	board = Board.objects.get(id=board_id)
	return render(request, 'board/detail.html', {
		'title': '디테일 페이지',
		'board': board
	})


def create(request):
	if request.method == "GET":
		return render(request, 'board/form.html', {
			'title': '입력폼',
		})
	else:
		board = Board()
		board.title = request.POST.get('title')
		board.content = request.POST.get('content')
		board.save()
		return redirect('/board/')


def update(request, board_id):
	board = Board.objects.get(id=board_id)
	if request.method == "GET":
		return render(request, 'board/form.html', {
			'title': '수정폼',
			'board': board
		})
	else:
		board.title = request.POST.get('title')
		board.content = request.POST.get('content')
		board.save()
		return redirect('/board/')


def delete(reqeust, board_id):
	Board.objects.get(id=board_id).delete()
	return redirect('/board/')

django/board_sample/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'articles:index' %}">MyBoard</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
			aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="{% url 'articles:create' %}">새글쓰기<span class="sr-only">(current)</span></a>
			<a class="nav-item nav-link" href="{% url 'articles:get_comments' %}">댓글보기<span class="sr-only">(current)</span></a>
		</div>
	</div>
</nav>
<div class="container">
{% block body %}

{% endblock %}
</div>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
	  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</body>
</html>

django/board_sample/articles/templates/articles/create_form.html
{% extends 'articles/base.html' %}
{% block title %}타이틀자리임{% endblock %}
{% block body %}
<form action="{% url 'articles:create' %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="title">제목</label>
		<input type="text" class="form-control" id="title" placeholder="제목을 입력해주세요" name="title">
	</div>
	<div class="form-group">
		<label for="content">내용</label>
		<textarea type="text" class="form-control" id="content" placeholder="내용을 입력해주세요" name="content"></textarea>
	</div>
	<button type="submit" class="btn btn-primary">등록</button>
</form>
{% endblock %}

django/board_sample/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<div class="card">
	<img src="https://picsum.photos/1024/150" class="card-img-top">
	<div class="card-body">
		<h5 class="card-title">글번호 : {{ article.title }} | 작성자 : {{ article.user }}</h5>
		<p class="card-text">내용 : {{ article.content }}</p>
		<a class="btn btn-info" href="{% url 'articles:update' article.id %}" role="button">수정</a>
		<a class="btn btn-danger" href="{% url 'articles:delete' article.id %}" role="button">삭제</a>
	</div>
</div>

<!--댓글 작성-->
<form action="{% url 'articles:create_comment' article.id %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="comment">댓글 달기</label>
		<input type="text" class="form-control" id="comment" name="content"
			   placeholder="입력해주세요">
	</div>
	<button type="submit" class="btn btn-outline-danger">댓글 등록</button>
</form>
{% for comment in article.comment_set.all %}
<div class="card my-3">
	<div class="card-body">
		<h5 class="card-title">{{comment.id}} 번 댓글 | 작성자 : {{comment.user}}</h5>
		<div class="d-flex bd-highlight">
			<div class="p-2 bd-highlight">{{comment.content}}</div>
			<div class="ml-auto p-2 bd-highlight"><a href="{% url 'articles:delete_comment' article.id comment.id %}" class="btn btn-outline-success">삭제 </a></div>
		</div>

	</div>
</div>
{% endfor %}
<!--댓글확인-->
{% endblock %}

django/board_sample/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<form method="POST">
	{% csrf_token %}
	<input type="hidden" name="id" value="{{ article.id }}">
	<div class="form-group">
		<label for="title">제목</label>
		<input type="text" class="form-control" id="title" placeholder="제목을 입력해주세요" name="title" value="{{ article.title }}">
	</div>
	<div class="form-group">
		<label for="content">내용</label>
		<textarea type="text" class="form-control" id="content" placeholder="내용을 입력해주세요" name="content">{{ article.content }}</textarea>
	</div>
	<button type="submit" class="btn btn-primary">등록</button>
</form>
{% endblock %}

django/board_sample/articles/templates/articles/get_comments.html
{% extends 'articles/base.html' %}
{% block title %}{{title}}{% endblock %}
{% block body %}
<h1>로그인한 유저 : {{ user }}</h1>
{% for comment in user.comment_set.all %}
<div class="alert alert-success" role="alert">
	{{ comment.content }}
</div>
{% endfor %}
{% endblock%}

django/board_sample/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<h1>{{ title }}</h1>
<table class="table">
	<thead>
	<tr>
		<th scope="col">번호</th>
		<th scope="col">제목</th>
		<th scope="col">작성자</th>
	</tr>
	</thead>
	<tbody>
	{% if articles %}
		{% for article in articles %}
		<tr onclick="location.href='{% url 'articles:detail' article.id %}'">
			<td>{{ article.id }}</td>
			<td>{{ article.title }}</td>
			<td>{{ article.user }}</td>
		</tr>
		{% endfor %}
	{% else %}
	<tr>
		<td colspan="3">글이 없습니다</td>
	</tr>
	{% endif %}
	</tbody>
</table>
{% endblock %}

django/board_sample/articles/templates/articles/update_form.html
{% extends 'articles/base.html' %}
{% block title %}타이틀자리임{% endblock %}
{% block body %}
<form action="{% url 'articles:update' %}" method="POST">
	{% csrf_token %}
	<input type="hidden" name="id" value="{{ article.id }}">
	<div class="form-group">
		<label for="title">제목</label>
		<input type="text" class="form-control" id="title" placeholder="제목을 입력해주세요" name="title" value="{{ article.title }}">
	</div>
	<div class="form-group">
		<label for="content">내용</label>
		<textarea type="text" class="form-control" id="content" placeholder="내용을 입력해주세요" name="content">{{ article.content }}</textarea>
	</div>
	<button type="submit" class="btn btn-primary">등록</button>
</form>
{% endblock %}

django/board_sample/board/templates/board/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'board:index' %}">보드홈</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'board:create' %}">새글쓰기</a>
			</li>
		</ul>
	</div>
</nav>
<div class="container">
	{% block body %}
	{% endblock %}
</div>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>
</body>
</html>

django/board_sample/board/templates/board/detail.html
{% extends 'board/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<div class="card" >
	<img src="https://picsum.photos/1024/150" class="card-img-top" alt="...">
	<div class="card-body">
		<h5 class="card-title">{{ board.title }}</h5>
		<p class="card-text">{{ board.content }}</p>
		<a class="btn btn-warning" href="{% url 'board:update' board.id %}" role="button">수정</a>
		<a class="btn btn-danger" href="{% url 'board:delete' board.id %}" role="button">삭제</a>
	</div>
</div>
{% endblock %}

django/board_sample/board/templates/board/form.html
{% extends 'board/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<form method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="title">제목</label>
		<input type="text" class="form-control" id="title" placeholder="제목을 입력해주세요" name="title"
			   value="{{ board.title }}">
	</div>
	<div class="form-group">
		<label for="content">내용</label>
		<textarea class="form-control" id="content" placeholder="내용을 입력해주세요"
				  name="content">{{ board.content }}</textarea>
	</div>
	<input type="submit" class="btn btn-primary" value="등록">
</form>
{% endblock %}

django/board_sample/board/templates/board/index.html
{% extends 'board/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<table class="table">
	<thead>
	<tr>
		<th scope="col">id</th>
		<th scope="col">제목</th>
		<th scope="col">내용</th>
	</tr>
	</thead>
	<tbody>
	{% if boards %}
	{% for board in boards %}
	<tr onclick="location.href='{% url 'board:detail' board.id %}'">
		<th scope="row">{{ board.id }}</th>
		<td>{{ board.title }}</td>
		<td>{{ board.content }}</td>
	</tr>
	{% endfor %}
	{% else %}
	<tr>
		<td colspan="3">글을 등록해주세요</td>
	</tr>
	{% endif %}
	</tbody>
</table>
{% endblock %}